project:
  type: website

# Metadata
pagetitle: "{{< meta title >}} | Claire Lepault"
description-meta: "Welcome! I am PhD candidate at the Paris School of Economics and CIRED."
author-meta: "Claire Lepault"

website:
  title: "Claire Lepault"
  description: "{{< meta description-meta >}}"
  navbar:
    background: "#95c7ac"
    search: true
    left:
      - text: "About"
        href: "index.qmd" 
      - CV.qmd
      - research.qmd
      - teaching.qmd
      - talks.qmd
      
    right:
      - icon: github
        href:  https://github.com/ClaireLepault

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



