project:
  type: website

website:
  title: "Claire Lepault"
  navbar:
    background: "#95c7ac"
    search: true
    left:
      - text: "About"
        href: "index.qmd" 
      - CV.qmd
      - research.qmd
      - outreach.qmd
      - teaching.qmd
      - toolbox.qmd
      


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto



